name: Main workflow

on: [push, pull_request]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    if:
      "!contains(github.event.head_commit.message, '[ci skip]') &&
      !startsWith(github.event.head_commit.message, 'docs')"
    strategy:
      matrix:
        node: ["18", "20"]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4.1.4

      - name: Set up Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint the workspaces
        run: npm run lint
